project:
  type: website
  output-dir: _site

website:
  title: "SIAM UQ 2026"
  navbar:
    left:
      - href: slides/intro.html
        text: Slides

format:
  html:
    toc: true

execute:
  warning: false
  message: false

