project:
  type: website
  output-dir: _site
  render:
    - index.qmd
  resources:
    - classlib/classlib/quarto/assets/**/*
    - classlib/classlib/notebooks/**/*

website:
  title: "SIAM UQ 2026"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: slides/SIAMUQ2026.html
        text: Slides
    right:
      - icon: github
        href: https://github.com/fjhickernell/SIAMUQ26

format:
  html:
    toc: true

execute:
  warning: false
  message: false

