---
title: "Low Discrepancy Drop-In Replacements for IID"
author: "Fred J. Hickernell"
subtitle: |
  Illinois Institute of Technology, hickernell@illinoistech.edu

  Joint work with Claude Hall, Jr., Jimmy Nguyen, Alexander Pride, Aleksei G. Sorokin, and the <span class="pkg">qmcpy</span> development team

  Supported in part by NSF-DMS-2316011 &nbsp; &nbsp; Thanks to the organizers

  SIAM Conference on Uncertainty Quantification (UQ26), Minneapolis, MN

  🔗 Slides: fjhickernell.github.io/SIAMUQ26/slides/SIAMUQ2026.html
date: 2026-03-23
date-format: "MMMM D, YYYY"

metadata-files:
  - ../classlib/classlib/quarto/slides/research/research-slides.yml

execute:
  echo: false

format:
  revealjs:
    code-overflow: wrap
---

# What quasi-Monte Carlo (QMC) does

{{< include setup.qmd >}}

:::{.columns}

::: {.column width="49%"}

For $\vx_0, \vx_1, \ldots \IIDsim \Unif[0,1]^d$
\begin{multline*}
\sqrt{\Ex\left[ \left( \int_{[0,1]^d} f(\vx) \, \dif \vx - \frac{1}{n} \sum_{i=0}^{n-1} f(\vx_i) \right)^2 \right]} \\
= \frac{\std(f)}{\alert{\sqrt{n}}}
\end{multline*}

:::

::: {.column width="2%"}
&nbsp;
:::

::: {.column width="49%"}

For [carefully]{.alert} chosen $\vx_0, \vx_1, \ldots \LDsim \Unif[0,1]^d$
\begin{multline*}
\left\lvert \int_{[0,1]^d} f(\vx) \, \dif \vx - \frac{1}{n} \sum_{i=0}^{n-1} f(\vx_i) \right\rvert
\\ \le \underbracket{\Dsc(\{\vx_i\}_{i=0}^{n-1})}_{\Order(\alert{n^{-1+\delta}}) \text{ or \class{alert}{better}}} \, \lVert f \rVert_{\cf}
\end{multline*}

:::

:::

:::{.columns}

::: {.column width="49%"}

```{python}
#| echo: false
#| fig-width: 4
#| fig-height: 4
#| fig-align: center
n_list = [16, 25, 64]
fig, ax = qp.plot_proj(
    qp.IIDStdUniform(d),
    n=n_list,
    d_horizontal=d_horiz,
    d_vertical=d_vert,
    figfac=4.7,
    axis_pad=axis_pad,
    where_title=0.93,
    marker_size=ms,
    fig_title=rf"$n = {', '.join(map(str, n_list))}$"
)
fig.tight_layout()
```
:::

::: {.column width="2%"}
&nbsp;
::: 

::: {.column width="49%"} 
```{python}
#| echo: false
#| fig-width: 4
#| fig-height: 4
#| fig-align: center

n_list = [16, 25, 64]
fig, ax = qp.plot_proj(
    qp.Lattice(d),
    n=n_list,
    d_horizontal=d_horiz,
    d_vertical=d_vert,
    figfac=4.7,
    axis_pad=axis_pad,
    where_title=0.93,
    marker_size=ms,
    fig_title=rf"Lattice $n = {', '.join(map(str, n_list))}$"
)
fig.tight_layout()
```

:::

:::



## Problem

::: {.columns}

::: {.column width="49%"}

### IID random sequences 
- [Extensible]{.alert}
  - Pause at any $n$ you like and add more points as needed
  - No problem if missing a few points here and there

- BUT convergence is [slow]{.alert}: $\Order(n^{-1/2})$

:::

::: {.column width="2%"}
&nbsp;
::: 

::: {.column width="49%"}

### Low discrepancy (LD) sequences

- [Faster]{.alert} convergence: $\Order(n^{-1+\delta})$ for any $\delta > 0$

- BUT 
    - Normally _not_ easily extensible in $n$
      - [Lattices]{.alert} [{{< meta papers.dickripil_2022_lattice_rules_book.cite >}}]({{< meta papers.dickripil_2022_lattice_rules_book.doi_url >}}): $n = 1, b, b^2, \ldots$ 
      - Digital nets: $n = 1, b, b^2, \ldots$ 
      - Halton: $n = 1, 2, 3, \ldots$ but bad projections in higher dimensions
      - [Kronecker]{.alert}: $n = 1, 2, 3, \ldots$ less studied
    - _Not_ robust to missing points
:::
:::

::: {.fragment}

### Want LD sequences that are _extensible_ in $n$ and _robust_ to missing points

- Cannot have $\Order(n^{-p})$ convergence with $p > 1$ for all $n$ 
- Need new constructions, error bounds, and stopping criteria

:::

## The sad and thrilling story of the missing, $\vx_0$

:::{.columns}

::: {.column width="49%"}

### Some libraries/users drop $\vx_0 = (0,\ldots,0)$ in a LD sequence

- $(0,\ldots,0)$ looks too regular
- Transforming $\LDsim \Unif[0,1]^d$ to $\LDsim\Norm(\vzero,\mI)$ $0 \to -\infty$ 

:::{.fragment}
The cure is to [randomize]{.alert} the sequence, not to drop points
:::

:::

::: {.column width="2%"}
&nbsp;  
:::

::: {.column width="49%"}

### This is a bad idea; keeping $\vx_0$

- Mainains balance that ensures low discrepancy

- Preserves the structure that allows for error bounds and stopping criteria, especially for Sobol' and lattice sequences for $n = 1, b, b^2, \ldots$

The LD community urges users and libraries to keep $\vx_0$ in the sequence, [(SciPy, success)](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.Sobol.html) and not to skip points [(MATLAB, not yet succeeded)](https://www.mathworks.com/help/stats/sobolset.html#btd9s8e-1) 
:::

:::

::: {.fragment}
But what if 

- There is [missing]{.alert} data, $f(\vx_{i_1}), f(\vx_{i_2}), \ldots, f(\vx_{i_k})$?  

- We [run out of budget]{.alert} before we reach the desired sample size?

:::


# The best we can hope for


[{{< meta papers.hickrikuonuy_2012_weighted_integration.cite >}}]({{< meta papers.hickrikuonuy_2012_weighted_integration.doi_url >}}) provides a way to handle missing data and stopping criteria for LD sequences


# What we can do so far

::: {.columns}

::: {.column width="49%"}

<h3>Lattice sequences</h3>

\begin{align*}
\vx_i &= \phi_b(i) \vzeta + \vDelta \bmod \vone \\
\boldsymbol{\zeta} & \in \mathbb{N}^d, \quad \boldsymbol{\Delta} \in [0,1)^d\\
\phi_b\bigl((\cdots i_2 i_1 i_0)_{b} \bigr) & = {}_b0.i_0 i_1 i_2 \cdots 
\end{align*}

:::

::: {.column width="2%"}
&nbsp;
:::


::: {.column width="49%"}  

<h3>Kronecker sequences</h3>

\begin{align*}
\boldsymbol{x}_i &= i\boldsymbol{\zeta} + \boldsymbol{\Delta} \bmod \boldsymbol{1} \\
\boldsymbol{\zeta}, \boldsymbol{\Delta} & \in [0,1)^d\\
\end{align*}

:::

:::

:::{.columns}

::: {.column width="49%"}

```{python}
#| echo: false
#| fig-width: 4
#| fig-height: 4
#| fig-align: center
n_list = [16, 25, 64]
fig, ax = qp.plot_proj(
    qp.Lattice(d),
    n=n_list,
    d_horizontal=d_horiz,
    d_vertical=d_vert,
    figfac=4.7,
    axis_pad=axis_pad,
    where_title=0.93,
    marker_size=ms,
    fig_title=rf"$n = {', '.join(map(str, n_list))}$"
)
fig.tight_layout()
```
:::

::: {.column width="2%"}
&nbsp;
::: 

::: {.column width="49%"} 
```{python}
#| echo: false
#| fig-width: 4
#| fig-height: 4
#| fig-align: center
n_list.append(97)
fig, ax = qp.plot_proj(
    qp.Kronecker(d),
    n=n_list,
    d_horizontal=d_horiz,
    d_vertical=d_vert,
    figfac=4.7,
    axis_pad=axis_pad,
    where_title=0.93,
    marker_size=ms,
    fig_title=rf"Kronecker $n = {', '.join(map(str, n_list))}$"
)
fig.tight_layout()
```

:::

:::

## Discrepancies and (weighted) expected squared discrepancies
\begin{align*}
\Dsc\bigl (\{\boldsymbol{x}_i\}_{i=0}^{n-1}, \mathcal{F} \bigr) &:= \sup_{\lVert f \rVert_{\cf} \le 1 }\left \lvert \int_{[0,1]^d} f(\boldsymbol{x}) \, \mathrm{d} \boldsymbol{x} - \frac 1n \sum_{i=0}^{n-1} f(\boldsymbol{x}_i) \right \rvert \\
\Dsc^2\bigl (\{\boldsymbol{x}_i\}_{i=0}^{n-1}, \mathcal{F} \bigr) & = 
\int_{[0,1]^d \times [0,1]^d} K(\boldsymbol{t}, \boldsymbol{x}) \, \mathrm{d} \boldsymbol{t}  \mathrm{d} \boldsymbol{x}
- \frac{2}{n} \sum_{i=0}^{n-1} \int_{[0,1]^d} K(\boldsymbol{x}_i, \boldsymbol{x}) \, \mathrm{d} \boldsymbol{x}
+ \frac{1}{n^2} \sum_{i,j=0}^{n-1} K(\boldsymbol{x}_i, \boldsymbol{x}_j)  \\
& \qquad \qquad \text{where } K \text{ is the reproducing kernel of the Hilbert space } \cf
\end{align*}

:::{.fragment}

$$
\ESD \bigl (\{\boldsymbol{x}_i\}_{i=0}^{n-1}, \mathcal{F} \bigr) := \Ex\left[ \Dsc^2\bigl (\{\boldsymbol{x}_i\}_{i=0}^{n-1}, \mathcal{F} \bigr) \right] \qquad 
\WESD (N,d) := \sum_{n=1}^N n \, \ESD \bigl (\{\boldsymbol{x}_i\}_{i=0}^{n-1}, \mathcal{F} \bigr)
$$

:::

## (Weighted) expected squared discrepancies for lattice and Kronecker sequences

\begin{align*}
\textrm{ESD}\bigl (\{\phi_b(i) \vzeta \}_{i=0}^{n-1} \ \class{alert}{\text{lattice}}, \mathcal{F} \bigr)
& = - \overline{K} + \frac 1{n^2} \biggl [ n \widetilde{K}(\boldsymbol{0}) +  \sum_{k=1}^{b^{\lceil \log_b n\rceil}-1} \#_n(k) \widetilde{K}\bigl( \phi_b(k) \boldsymbol{\zeta}\bigr) \biggr] \\
\textrm{ESD}\bigl (\{i \vzeta \}_{i=0}^{n-1}\ \class{alert}{\text{Kronecker}}, \mathcal{F} \bigr) 
& = - \overline{K} + \frac 1{n^2} \biggl [ n \widetilde{K}(\boldsymbol{0}) + 2 \sum_{k=1}^{n -1}(n - k) \widetilde{K}( k \boldsymbol{\zeta}) \biggr] \\
\widetilde{K}(\boldsymbol{x}) &: = \int_{[0,1]^d} K(\boldsymbol{x} + \boldsymbol{y} \bmod \boldsymbol{1}, 
\boldsymbol{y}) \, \mathrm{d} \boldsymbol{y} \qquad
\overline{K} : = \int_{[0,1]^d} \widetilde{K}(\boldsymbol{x}) \, \mathrm{d} \boldsymbol{x}\\
\#_n(k) &: = \mathrm{card}\bigl \{k : \phi_b(k) = \phi_b(i) - \phi_b(j) \bmod 1 \text{ s.t. } i, j, \in \{0, \ldots, n-1 \} \bigr\} \\
\WESD (N,d)  & := \sum_{n=1}^N n \, \ESD \bigl (\{\boldsymbol{x}_i\}_{i=0}^{n-1}, \mathcal{F} \bigr) \qquad \text{in } \class{alert}{\Order(N)} \text{ operations}
\end{align*}


## Component-by-component (CBC) constructions

1. For $d=1$, choose $\zeta_1$ to minimize $\textrm{WSESD}(N, d)$

2. For $d = 2, \ldots, d_{\max}$, choose $\zeta_d$ to minimize $\textrm{WSESD} (N, d)$, given the previously chosen $\zeta_1, \ldots, \zeta_{d-1}$

```{python}
#| echo: false
gamma = np.arange(1,d+1)**-2.
n = 1_000_000
n_vals = np.arange(1,n+1)
discIID = np.sqrt((-1+np.prod(1+gamma/6))/n_vals)
n_which_trend = np.array(n_vals[999:-1])
```

:::{.fragment}


:::{.columns}

::: {.column width="49%"}
Ours vs IID and CBC by [{{< meta papers.cookuonuy_2006_constructing_embedded.cite >}}]({{< meta papers.cookuonuy_2006_constructing_embedded.doi_url >}})
```{python}
#| echo: false
#| fig-width: 4
#| fig-height: 4
#| fig-align: center

CBC_lattice_disc = np.loadtxt("CBC_Disc_d_13_n_1048576.txt",delimiter=",")
CBC_lattice_disc = CBC_lattice_disc[:n]
Kuo_lattice_disc = np.loadtxt("Kuo_Disc_d_13_n_1048576.txt",delimiter=",")
Kuo_lattice_disc = Kuo_lattice_disc[:n]

fig, ax = plt.subplots()
ax.set_aspect('equal')
ax.loglog(n_vals,discIID, label = "IID")
ax.loglog(n_vals,Kuo_lattice_disc, label = "CKN06 CBC")
ax.loglog(n_vals,CBC_lattice_disc, label = "Our CBC")
power, coef = nb.plot_log_trend_line(ax, n_vals, CBC_lattice_disc,n_which=n_which_trend)
powers_of_two_idx = np.array([2**k for k in range(6,20)])-1  #look at preferred n
power_Kuo, coef_Kuo = nb.plot_log_trend_line(ax, n_vals, Kuo_lattice_disc, n_which=powers_of_two_idx, 
                                     w=1, endpoints = (1,n))
ax.loglog(n_vals[powers_of_two_idx],Kuo_lattice_disc[powers_of_two_idx],'.', ms=10, color=nb.TOL_BRIGHT["cyan"])

ax.set_xlabel("$n$")
ax.set_ylabel("RMS Discrepancy")
ngamma = 4
gamma_str = ", ".join(f"{g:.2f}" for g in gamma[:ngamma])
if len(gamma) > ngamma:
    gamma_str += ", …"   # ellipsis at the end
ax.set_title(rf"Lattice, $d = {d}, \boldsymbol{{\gamma}} = ({gamma_str})$")
ax.set_xlim(1, 1e6) 
ax.set_ylim(1e-6, 1)
ax.legend(loc="lower left",fontsize=20)
fig.tight_layout();
```
:::

::: {.column width="2%"}
&nbsp;
:::

::: {.column width="49%"}

Ours vs IID, [{{< meta papers.richtmyer_1951_sequences.cite >}}]({{< meta papers.richtmyer_1951_sequences.project_url >}}), and [{{< meta papers.dicgodlarpilsuz_2025_quasi-uniformity.cite >}}]({{< meta papers.dicgodlarpilsuz_2025_quasi-uniformity.doi_url >}})
```{python}
#| echo: false
#| fig-width: 4
#| fig-height: 4
#| fig-align: center

Kron_params = {
    "R51": "Richtmyer",
    "DGLPS25": "Suzuki",
    "Our CBC": "CBC"
}

fig, ax = plt.subplots()
ax.set_aspect('equal')
ax.loglog(n_vals,discIID, label = "IID")
Kron_discrepancies = {}   # dictionary to hold results
for label, which_alpha in Kron_params.items():
    disc = qp.Kronecker(dimension = d, generating_vector = which_alpha, 
                        randomize=False).periodic_discrepancy(n, gamma=gamma)
    Kron_discrepancies[label] = disc
    ax.loglog(n_vals, disc, label=f"{label}")

power, coef = nb.plot_log_trend_line(ax, n_vals, Kron_discrepancies["Our CBC"],
    n_which=n_which_trend)
    
ax.set_xlabel("$n$")
ax.set_ylabel("RMS Discrepancy")
ngamma = 4
gamma_str = ", ".join(f"{g:.2f}" for g in gamma[:ngamma])
if len(gamma) > ngamma:
    gamma_str += ", …"   # ellipsis at the end
ax.set_title(rf"Kronecker, $d = {d}, \boldsymbol{{\gamma}} = ({gamma_str})$")
ax.set_xlim(1, 1e6) 
ax.set_ylim(1e-6, 1)
ax.legend(loc="lower left",fontsize=20)
fig.tight_layout();

```

:::


:::

:::

## An Asian option example






# Implementation

`qmcpy` is an open source Python library for quasi-Monte Carlo methods

- Provides implementations of various low discrepancy sequences, including lattice and Kronecker sequences
- Includes tools for error estimation and stopping criteria
- <span id="qmcpy-pypi-impact">Loading PyPI impact metric...</span>
- In active development with contributions from the community

# Further work


# References

::: {.refs}

[{{< meta papers.cookuonuy_2006_constructing_embedded.cite >}}]{.ref-label}
{{< meta papers.cookuonuy_2006_constructing_embedded.full >}}
[DOI]({{< meta papers.cookuonuy_2006_constructing_embedded.doi_url >}}) · 
[arXiv]({{< meta papers.cookuonuy_2006_constructing_embedded.arxiv_url >}}) · 
[publisher]({{< meta papers.cookuonuy_2006_constructing_embedded.publisher_url >}}) · 
[project]({{< meta papers.cookuonuy_2006_constructing_embedded.project_url >}})


[{{< meta papers.dickripil_2022_lattice_rules_book.cite >}}]{.ref-label}
{{< meta papers.dickripil_2022_lattice_rules_book.full >}}
[DOI]({{< meta papers.dickripil_2022_lattice_rules_book.doi_url >}}) · 
[publisher]({{< meta papers.dickripil_2022_lattice_rules_book.publisher_url >}})


[{{< meta papers.hickrikuonuy_2012_weighted_integration.cite >}}]{.ref-label}
{{< meta papers.hickrikuonuy_2012_weighted_integration.full >}}
[DOI]({{< meta papers.hickrikuonuy_2012_weighted_integration.doi_url >}}) ·  
[publisher]({{< meta papers.hickrikuonuy_2012_weighted_integration.publisher_url >}})


[{{< meta papers.richtmyer_1951_sequences.cite >}}]{.ref-label}
{{< meta papers.richtmyer_1951_sequences.full >}}
[project]({{< meta papers.richtmyer_1951_sequences.project_url >}})


:::


# Proofs{#proofs}

For a fixed Banach space of integrands, $\cf$, we have bounds on the discrepancy of any $n$-point set, $\{\vt_i\}_{i=0}^{n-1}$:

$$
0 < a n^{-Q} \le \inf_{\{\vt_i\}_{i=0}^{n-1} \subset [0,1]^d} \Dsc(\{\vt_i\}_{i=0}^{n-1}) \le \sup _{\{\vt_i\}_{i=0}^{n-1} \subset [0,1]^d} \Dsc(\{\vt_i\}_{i=0}^{n-1})\le A, \qquad n = 1, 2, \ldots
$$


And also that for a specific sequence of nodes, $\{\vx_i\}_{i=0}^{\infty}$ and a sequence of sample sizes, $1 \le n_1 < n_2 < \ldots$, we have better bounds on the discrepancy:

$$
c n_k^{-P} \le \Dsc(\{\vx_i\}_{i=0}^{n_k-1}) \le C n_k^{-p} \qquad k = 1, 2, \ldots
$$

where $p \le P \le Q$.

## testing
